### ISSUE TITLE
Make important development decisions

### ISSUE THREAD

**Issue by finnnnnnnnnnnnnnnnn** [HellFire-Creators/HellFire-Site#6]
### Todo
- [ ] Choose a frontend framework
- [ ] Choose a backend framework
- [ ] Choose a CSS framework
- [ ] Choose a host
- [ ] Anything else
